// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALK8IgIdsPeSbOI7vne9phoxbaY0AvjpY',
    appId: '1:818967567121:web:65255df9c83496bb780ab0',
    messagingSenderId: '818967567121',
    projectId: 'kloof-1cfcd',
    authDomain: 'kloof-1cfcd.firebaseapp.com',
    storageBucket: 'kloof-1cfcd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYa0N8L4C4WZss4h5MD9iQpU3L32Z7QeM',
    appId: '1:818967567121:android:34685166e0b5d723780ab0',
    messagingSenderId: '818967567121',
    projectId: 'kloof-1cfcd',
    storageBucket: 'kloof-1cfcd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPCQ6BNaizmGrAx2JChe0Xz7WKdSBrVgM',
    appId: '1:818967567121:ios:269a032aed817e1e780ab0',
    messagingSenderId: '818967567121',
    projectId: 'kloof-1cfcd',
    storageBucket: 'kloof-1cfcd.firebasestorage.app',
    iosBundleId: 'com.example.kloof',
  );
}
